import Csharp from '../assets/stack-2/Csharp.svg'
import Netcore from '../assets/stack-2/NetCore.svg'
import AspNet from '../assets/stack-2/AspNet.svg'
import Java from '../assets/stack-2/Java-Dark.svg'
import Python from '../assets/stack-2/Python-Dark.svg'
import CPP from '../assets/stack-2/CPP.svg'
import Angular from '../assets/stack-2/Angular.svg'
import JS from '../assets/stack-2/JavaScript.svg'
import TS from '../assets/stack-2/TypeScript.svg'
import NodeJS from '../assets/stack-2/NodeJS-Dark.svg'
import ReactJS from '../assets/stack-2/ReactJS-Dark.svg'
import ExpressJS from '../assets/stack-2/ExpressJS-Dark.svg'
import MongoDB from '../assets/stack-2/MongoDB.svg'
import Redux from '../assets/stack-2/Redux.svg'
import TailwindCSS from '../assets/stack-2/Tailwind-Dark.svg'
import HTML from '../assets/stack-2/HTML.svg'
import CSS from '../assets/stack-2/CSS.svg'
import Git from '../assets/stack-2/Git.svg'
import GitHub from '../assets/stack-2/Github-Dark.svg'
import WebSockets from '../assets/stack-2/WebSockets.svg'
import MySQL from '../assets/stack-2/MySQL-Dark.svg'
import PostgreSQL from '../assets/stack-2/PostgreSQL-Dark.svg'
import Spring from '../assets/stack-2/Spring-Dark.svg'
import SpringBoot from '../assets/stack-2/SpringBoot.svg'
import SpringData from '../assets/stack-2/Spring Data.svg'
import Hibernate from '../assets/stack-2/Hibernate-Dark.svg'
import Postman from '../assets/stack-2/Postman.svg'
import Maven from '../assets/stack-2/Maven-Dark.svg'
import Gradle from '../assets/stack-2/Gradle-Dark.svg'
import NextJS from '../assets/stack-2/NextJS-Dark.svg'
import Redis from '../assets/stack-2/Redis-Dark.svg'
import GraphQL from '../assets/stack-2/GraphQL-Dark.svg'
import Docker from '../assets/stack-2/Docker.svg'
import Mongoose_D from '../assets/stack-2/Mongoose-Dark.svg'
import Mongoose_L from '../assets/stack-2/Mongoose.svg'
import Prisma from '../assets/stack-2/Prisma.svg'
import Azure from '../assets/stack-2/Azure.svg'
import AWS from '../assets/stack-2/AWS-Dark.svg'
import Firebase from '../assets/stack-2/Firebase-Dark.svg'
import Figma from '../assets/stack-2/Figma-Dark.svg'

export default [
  Csharp, Netcore, AspNet, Java, Python, CPP, Angular, JS, TS, ReactJS, NextJS,
  NodeJS, ExpressJS, SpringBoot, SpringData, Hibernate, PostgreSQL, MySQL,
  MongoDB, Redis, Prisma, Redux, HTML, CSS, TailwindCSS, WebSockets,
  Git, GitHub, Postman, Docker, Azure, AWS
]
